services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: microbiology
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cheese
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080