services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: microbiology
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: cheese
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

  app:
    image: openjdk
    volumes:
      - ./build/libs:/usr/src/app
      - ./src/release:/usr/src/app/config
    working_dir: /usr/src/app
    ports:
      - 8081:8081
    links: 
      - db
    command: ["java", "-jar", "/usr/src/app/cheeze-api-0.0.1-SNAPSHOT.jar", "--spring.config.location=config/application.release.properties"]